name: Build Docs

on:
  push:
    branches: [main]
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install pipx
        run: |
          python -m pip install --upgrade pip
          python -m pip install --user pipx
          python -m pipx ensurepath

      - name: Install Poetry via pipx
        run: pipx install poetry
          
      - name: Install project dependencies
        run: poetry install  # installs your package and dependencies

      - name: Build docs
        run: poetry run make -C docs html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages        # branch to deploy to
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html   # output folder from `make html`
          force_orphan: true     
